version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.0
    # volumes:
    #   - /docker/elasticsearch/data:/usr/share/elasticsearch/data
    command: elasticsearch -Des.cluster.name="logstashtic"
    ports:
      - '9200:9200'

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - '8080:15672'
      - '4369:4369'
      - '5671-5672:5671-5672'
      - '15671:15671'
      - '25672:25672'

  logstash-consumer:
    image: logstash:6.6.0
    links:
      - rabbitmq
      - elasticsearch
    volumes:
      - ./config:/usr/share/logstash/config/test
    command: bin/logstash -f /usr/share/logstash/config/test/logstash.conf
    # command: logstash -f /config/consumer.conf
  kibana:
    image: kibana:4.2
    links:
      - elasticsearch
    ports:
      - '5601:5601'
#   zookeeper:
#     image: 'bitnami/zookeeper:latest'
#     ports:
#       - '2181:2181'
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#   kafka:
#     image: 'bitnami/kafka:latest'
#     ports:
#       - '9092:9092'
#     environment:
#       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#       - ALLOW_PLAINTEXT_LISTENER=yes
