apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: openfaas-logging
spec:
  serviceName: 'rabbitmq'
  selector:
    matchLabels:
      run: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        run: rabbitmq
    spec:
      serviceAccountName: rabbitmq
      terminationGracePeriodSeconds: 10
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - name: queue-port
              containerPort: 5672
            - name: management-port
              containerPort: 15672
            - name: cluster-port
              containerPort: 4369
            - name: dist-port
              containerPort: 25672
          livenessProbe:
            exec:
              command: ['rabbitmqctl', 'status']
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 15
          readinessProbe:
            exec:
              command: ['rabbitmqctl', 'status']
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 10
          imagePullPolicy: Always
